#include "mainwindow.h"
#include "./ui_mainwindow.h"

void MainWindow::setStyleDark(){
    qApp->setStyleSheet(
        // --- Базовые контейнеры ---
        "QMainWindow, QDialog, QWidget {"
        "    background-color: rgb(26, 27, 29);"
        "    color: rgb(255, 255, 255);"
        "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"
        "    font-size: 14px;"
        "}"
        // --- Кнопки ---
        "QPushButton {"
        "    background-color: rgb(44, 45, 47);"
        "    color: rgb(255, 255, 255);"
        "    border: 1px solid rgb(58, 59, 60);"
        "    border-radius: 8px;"
        "    padding: 8px 16px;"
        "    font-size: 14px;"
        "}"
        "QPushButton:hover {"
        "    background-color: rgb(54, 55, 57);"
        "    border-color: rgb(15, 203, 255);"
        "}"
        "QPushButton:pressed {"
        "    background-color: rgb(34, 35, 37);"
        "}"
        "QPushButton:disabled {"
        "    background-color: rgb(34, 35, 37);"
        "    color: rgb(128, 128, 128);"
        "}"
        // --- Стили для кнопок в списке чатов (по objectName 'chat-button') ---
        "QPushButton#chat-button {"
        "    background-color: rgb(36, 37, 39);"
        "    color: rgb(255, 255, 255);"
        "    border: 1px solid rgb(41, 56, 71);"
        "    border-radius: 8px;"
        "    padding: 12px 8px;"
        "    text-align: left;"
        "    font-size: 14px;"
        "    margin: 2px 0px;"
        "}"
        "QPushButton#chat-button:hover {"
        "    background-color: rgb(44, 45, 47);"
        "    border-color: rgb(15, 203, 255);"
        "}"
        "QPushButton#chat-button:pressed {"
        "    background-color: rgb(47, 53, 63);"
        "}"
        // --- Текстовое поле ввода ---
        "QTextEdit {"
        "    background-color: rgb(36, 37, 39);"
        "    color: rgb(255, 255, 255);"
        "    border: 1px solid rgb(58, 59, 60);"
        "    border-radius: 8px;"
        "    padding: 8px;"
        "    font-size: 14px;"
        "    selection-background-color: rgb(15, 203, 255);"
        "}"
        "QTextEdit:focus {"
        "    border-color: rgb(15, 203, 255);"
        "}"
        // --- Списки и области прокрутки ---
        "QListView {"
        "    background-color: rgb(36, 37, 39);"
        "    color: rgb(255, 255, 255);"
        "    border: 1px solid rgb(58, 59, 60);"
        "    border-radius: 8px;"
        "    padding: 8px;"
        "    font-size: 16px;"
        "    font-weight: bold;"
        "}"
        "QListView::item {"
        "    padding: 8px;"
        "    border-bottom: 1px solid rgb(44, 45, 47);"
        "}"

        "QScrollArea {"
        "    background-color: rgb(36, 37, 39);"
        "    border: 1px solid rgb(58, 59, 60);"
        "    border-radius: 8px;"
        "}"
        // scrollArea
        "QScrollArea#scrollAreaListChat { background-color: rgb(32, 33, 35); }"
        "QScrollArea#scrollAreaMessage { background-color: rgb(28, 29, 31); }"
        // --- Скроллбары ---
        "QScrollBar:vertical {"
        "    background-color: rgb(32, 33, 35);"
        "    width: 12px;"
        "    border-radius: 6px;"
        "    margin: 0px;"
        "    border: none;"
        "}"
        "QScrollBar::handle:vertical {"
        "    background-color: rgb(68, 69, 71);"
        "    border-radius: 6px;"
        "    min-height: 20px;"
        "    margin: 2px;"
        "}"
        "QScrollBar::handle:vertical:hover {"
        "    background-color: rgb(88, 89, 91);"
        "    border-radius: 6px;"
        "}"
        "QScrollBar::handle:vertical:pressed {"
        "    background-color: rgb(108, 109, 111);"
        "    border-radius: 6px;"
        "}"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
        "    height: 0px;"
        "    border: none;"
        "    background: none;"
        "    border-radius: 6px;"
        "}"
        "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {"
        "    background: none;"
        "    border-radius: 6px;"
        "}"

        "QScrollBar:horizontal {"
        "    background-color: rgb(32, 33, 35);"
        "    height: 12px;"
        "    border-radius: 6px;"
        "    margin: 0px;"
        "    border: none;"
        "    border-radius: 6px;"
        "}"
        "QScrollBar::handle:horizontal {"
        "    background-color: rgb(68, 69, 71);"
        "    border-radius: 6px;"
        "    min-width: 20px;"
        "    margin: 2px;"
        "    border-radius: 6px;"
        "}"
        "QScrollBar::handle:horizontal:hover {"
        "    background-color: rgb(88, 89, 91);"
        "    border-radius: 6px;"
        "}"

        // --- Сообщения ---
        // contentWidget->setObjectName("message-bubble-my") / "message-bubble-other"
        "QWidget#message-bubble-my {"
        "    background-color: rgb(17, 49, 58);"
        "    color: rgb(233, 234, 236);"
        "    border-radius: 12px;"
        "    padding: 8px;"
        "    margin: 4px;"
        "}"
        "QWidget#message-bubble-other {"
        "    background-color: rgb(44, 45, 47);"
        "    color: rgb(254, 254, 254);"
        "    border-radius: 12px;"
        "    padding: 8px;"
        "    margin: 4px;"
        "}"
        // --- Текст и время ---
        "QLabel#message-text, QLabel#message-text-my {"
        "    background: transparent;"
        "    border: none;"
        "    padding: 0px;"
        "    color: rgb(254, 254, 254);"
        "    font-size: 14px;"
        "}"
        "QLabel#message-time, QLabel#message-time-my {"
        "    background: transparent;"
        "    font-size: 11px;"
        "    color: rgb(168, 168, 168);"
        "}"
        "QLabel#message-time-my { color: rgb(168, 168, 168); }"
    );
}


void MainWindow::setStyleLight(){
    qApp->setStyleSheet(
        // --- Базовые контейнеры ---
        "QMainWindow, QDialog, QWidget {"
        "    background-color: rgb(248, 248, 248);"
        "    color: rgb(0, 0, 0);"                  
        "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"
        "    font-size: 14px;"
        "}"
        // --- Кнопки ---
        "QPushButton {"
        "    background-color: rgb(240, 240, 240);" 
        "    color: rgb(0, 0, 0);"                  
        "    border: 1px solid rgb(200, 200, 200);" 
        "    border-radius: 8px;"
        "    padding: 8px 16px;"
        "    font-size: 14px;"
        "}"
        "QPushButton:hover {"
        "    background-color: rgb(230, 230, 230);"  
        "    border-color: rgb(0, 122, 255);"      
        "}"
        "QPushButton:pressed {"
        "    background-color: rgb(220, 220, 220);"  
        "}"
        "QPushButton:disabled {"
        "    background-color: rgb(245, 245, 245);"
        "    color: rgb(150, 150, 150);"       
        "}"
        // --- Стили для кнопок в списке чатов (по objectName 'chat-button') ---
        "QPushButton#chat-button {"
        "    background-color: rgb(255, 255, 255);" 
        "    color: rgb(0, 0, 0);"                  
        "    border: 1px solid rgb(220, 220, 220);" 
        "    border-radius: 8px;"
        "    padding: 12px 8px;"
        "    text-align: left;"
        "    font-size: 14px;"
        "    margin: 2px 0px;"
        "}"
        "QPushButton#chat-button:hover {"
        "    background-color: rgb(245, 245, 245);" 
        "    border-color: rgb(0, 122, 255);"       
        "}"
        "QPushButton#chat-button:pressed {"
        "    background-color: rgb(235, 235, 235);" 
        "}"
        // --- Текстовое поле ввода ---
        "QTextEdit {"
        "    background-color: rgb(255, 255, 255);"  
        "    color: rgb(0, 0, 0);"                  
        "    border: 1px solid rgb(200, 200, 200);"
        "    border-radius: 8px;"
        "    padding: 8px;"
        "    font-size: 14px;"
        "    selection-background-color: rgb(0, 122, 255);" 
        "}"
        "QTextEdit:focus {"
        "    border-color: rgb(0, 122, 255);"      
        "}"
        // --- Списки и области прокрутки ---
        "QListView {"
        "    background-color: rgb(255, 255, 255);" 
        "    color: rgb(0, 0, 0);"                 
        "    border: 1px solid rgb(200, 200, 200);"
        "    border-radius: 8px;"
        "    padding: 8px;"
        "    font-size: 16px;"
        "    font-weight: bold;"
        "}"
        "QListView::item {"
        "    padding: 8px;"
        "    border-bottom: 1px solid rgb(240, 240, 240);" 
        "}"

        "QScrollArea {"
        "    background-color: rgb(255, 255, 255);" 
        "    border: 1px solid rgb(200, 200, 200);"
        "    border-radius: 8px;"
        "}"
        // scrollArea
        "QScrollArea#scrollAreaListChat { background-color: rgb(245, 245, 245); }"  
        "QScrollArea#scrollAreaMessage { background-color: rgb(250, 250, 250); }"   
        // --- Скроллбары ---
        "QScrollBar:vertical {"
        "    background-color: rgb(245, 245, 245);"  
        "    width: 12px;"
        "    border-radius: 6px;"
        "    margin: 0px;"
        "}"
        "QScrollBar::handle:vertical {"
        "    background-color: rgb(200, 200, 200);"  
        "    border-radius: 6px;"
        "    min-height: 20px;"
        "}"
        "QScrollBar::handle:vertical:hover { background-color: rgb(170, 170, 170); }"  
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0px; border: none; background: none; }"
        "QScrollBar:horizontal {"
        "    background-color: rgb(245, 245, 245);"  
        "    height: 12px;"
        "    border-radius: 6px;"
        "    margin: 0px;"
        "}"
        "QScrollBar::handle:horizontal {"
        "    background-color: rgb(200, 200, 200);"
        "    border-radius: 6px;"
        "    min-width: 20px;"
        "}"
        // --- Сообщения ---
        // contentWidget->setObjectName("message-bubble-my") / "message-bubble-other"
        "QWidget#message-bubble-my {"
        "    background-color: rgb(106, 28, 126);"   
        "    color: rgb(255, 255, 255);"            
        "    border-radius: 12px;"
        "    padding: 8px;"
        "    margin: 4px;"
        "}"
        "QWidget#message-bubble-other {"
        "    background-color: rgb(240, 240, 240);"  
        "    color: rgb(0, 0, 0);"                 
        "    border-radius: 12px;"
        "    padding: 8px;"
        "    margin: 4px;"
        "}"
        // --- Текст и время ---
        "QLabel#message-text, QLabel#message-text-my {"
        "    background: transparent;"
        "    border: none;"
        "    padding: 0px;"
        "    color: rgb(0, 0, 0);"                  
        "    font-size: 14px;"
        "}"
        "QLabel#message-text-my {"
        "    color: rgb(255, 255, 255);"           
        "}"
        "QLabel#message-time, QLabel#message-time-my {"
        "    background: transparent;"
        "    font-size: 11px;"
        "    color: rgb(120, 120, 120);"           
        "}"
        "QLabel#message-time-my { color: rgba(255, 255, 255, 0.8); }" 
    );
}
